#!/usr/bin/env ruby

require './lib/options'

options = Options.new

if options.valid?
  require './lib/converter'
  converter = Converter.new(options)

  converter.convert.last_result.each {|key, val| puts "#{key}: #{val}"}
else
  options.errors.each {|msg| puts msg}
end
